CREATE TABLE students (
	id BIGINT PRIMARY KEY NOT NULL,
	name VARCHAR(150) NOT NULL,
	dob DATE NOT NULL,
	gender GENDER NOT NULL,
	email_id VARCHAR(100) UNIQUE NOT NULL ,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL
);